version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}
    elasticsearch: {}
networks:
  elk:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
  elasticsearch:
    image: elasticsearch:6.5.3
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk
    expose:
      - 9200
    ports:
      - 9200:9200
  kibana:
    image: kibana:6.5.3
    networks:
      - elk
    expose:
      - 5601
    ports:
      - 5601:5601